# 1. Scenario: You have a list of integers, and you need to find the maximum value in the list.
## a. How would you find the maximum value from the following list?

We can sort the number in ascending order and the last value would be the maximum.

In [15]:
#Given list of numbers
num = [90,45,81,100,20,56,95]

#Arrange in ascending order
num.sort()
num


#Find the maximum value
max_num = num[-1] #because the last element will be the maximum
max_num #output

100

# 2. Scenario: You need to concatenate a list of strings into a single string, with each string separated by a comma.
## a. Question: How would you combine the following list of strings into a single string?

We can use the "+" sign to concatenate the list of strings.

In [16]:
# Given lists of strings
a = ["lion", "tiger", "elephant"]
b = ["cat", "dog", "bat"]

# Concatenate lists a and b 
a + b #output

['lion', 'tiger', 'elephant', 'cat', 'dog', 'bat']

# 3. Scenario: You have a dictionary where the keys are names and the values are ages. You need to retrieve the age of a specific person.
## a. Question: How would you get the age of "Dev" from the following dictionary?

We can use dictionary lookup function.

In [21]:
#Dictonary
name_age = {"Ram": 24, "Dev": 30, "Sam": 35, "Prakash": 40}

#Get and print age of Dev
age_of_Dev = name_age["Dev"]
print(age_of_Dev)

30


# 4. Scenario: You need to remove duplicate elements from a list while preserving the original order of elements.
## a. Question: How would you remove duplicates from the following list?

We can use np.unique function from numpy library.

In [32]:
#import numpy library
import numpy as np

#original list of numbers
num = [1,1,3,4,6,12,4,6,31]

#remove duplicate elements while keeping the original order
np.unique(num) #output


array([ 1,  3,  4,  6, 12, 31])

# 5. Scenario: You have a NumPy array and need to compute the sum of all its elements.
## a. Question: How would you find the sum of elements in the following NumPy array?

We can find the sum using the sum() function.

In [38]:
#Given numpy array
array1 = np.array([1,3,4,2,6])

#Calculating the sum of elements in the given array
sum(array1)

16

# 6. Scenario: You have a 2D NumPy array and need to get the maximum value from each column.
## a. Question: How would you find the maximum values for each column in the following array?

We can use np.max() function.

In [47]:
#Create 2D array
array2 = np.array([[1,6,7], [5,3,4], [0,12,2]])
print(array2)

#Generate the maximum values from each column
max_values = np.max(array2, axis = 0) #Axis = 0 means vertical i.e. column
print(max_values)

[[ 1  6  7]
 [ 5  3  4]
 [ 0 12  2]]
[ 5 12  7]


# 7. Scenario: You have a DataFrame and need to sort it by a specific column.
## a. Question: How would you sort the DataFrame by the "Age" column?

We can import pandas library and use sort_values(by = "Age") function.

# 8. Scenario: You need to calculate the total sum of a column in a DataFrame.
## a. Question: How would you find the sum of the "Sales" column?

We can use DataFrame["Sales"].sum().

# 9. Scenario: You need to check if a variable is of type int.
## a. Question: How would you verify if a variable x is an integer?

We can use type(x).

In [49]:
x = 10
type(x)

int

# 10.Scenario: You have a list of mixed types and need to create separate lists for integers, floats, and strings.
## a. Question: How would you categorize the following mixed list into different types?

In [2]:
mixed_list = [1,2.5,"apple",3,"orange",4.8]

integers = []
floats = []
strings = []

for item in mixed_list:
    if isinstance(item, int):
        integers.append(item)
    elif isinstance(item, float):
        floats.append(item)
    elif isinstance(item, str):
        strings.append(item)

print("Integers:", integers)
print("Floats:", floats)
print("Strings:", strings)

#Used online source

Integers: [1, 3]
Floats: [2.5, 4.8]
Strings: ['apple', 'orange']


# 11.Scenario: You are given a string of comma-separated numbers. You need to convert this string into a list of integers.
## a. Question: How would you achieve this conversion?

In [9]:
num_string = "1, 2, 3, 4, 5, 6"
type(num_string)

#Split the string by commas
str_list = num_string.split(',')
str_list

['1', ' 2', ' 3', ' 4', ' 5', ' 6']

In [10]:
int_list = []

for num in str_list:
    int_value = int(num.strip()) #remove white space and convert into integer
    int_list.append(int_value)
print(int_list)

[1, 2, 3, 4, 5, 6]


# 12.Scenario: You need to reverse the words in a sentence while keeping the order of the words intact.
## a. Question: How would you reverse each word in the following sentence?

In [76]:
sentence = "I am a student"

words = sentence.split()

type(words)

reverse_words = reversed(words)
list(reverse_words)

['student', 'a', 'am', 'I']

# 13.Scenario: You need to combine two lists into a dictionary where the elements of the first list are keys and the elements of the second list are values.
## a. Question: How would you combine the following lists into a dictionary?

In [13]:
keys = ["Field", "Salary", "State"]
values = ["Computer Science", 100000, "Virginia"]

In [15]:
#Using zip() to pair elements from both list
paired = zip(keys, values)

#Converting the paired elements into a dictionary
result_dict = dict(paired)

# Step 3: Print the resulting dictionary
print(result_dict)

{'Field': 'Computer Science', 'Salary': 100000, 'State': 'Virginia'}


# 14.Scenario: You are given a list of tuples where each tuple contains a name and an age. You need to sort this list by age.
## a. Question: How would you sort the following list of tuples by age?

In [18]:
person = [("Ram", 32), ("Shyam", 21), ("Sita", 30)]

In [20]:
#Using sorted() with a key to sort by the second element whch is 'age'
sorted_person = sorted(person, key = lambda x: x[1])

#Printing the sorted list
print(sorted_person)

[('Shyam', 21), ('Sita', 30), ('Ram', 32)]


## Using online resources
### sorted(people, key=lambda x: x[1]): The sorted() function sorts the list. The key=lambda x: x[1] part tells Python to sort by the second element of each tuple (x[1]), which is the age.
### lambda x: x[1]: This is an anonymous function (lambda function) that takes each tuple x and returns its second element (x[1]), which is used for sorting.

# 15.Scenario: You have a 2D NumPy array and need to calculate the mean value of each row.
## a. Question: How would you compute the mean value for each row in the following array?

In [79]:
#Create 2D array
array3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array3)

#calculate mean of each row
row_mean = np.mean(array3, axis = 1) #axis 1 is horizontal
print(row_mean)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2. 5. 8.]


# 16.Scenario: You need to create a NumPy array of size 10 filled with zeros, and then set the fifth element to 5.
## a. Question: How would you create and modify the array as described?

In [83]:
#create numpy array of size 10 filled with zeros
array4 = np.zeros(10)

#set the fifth element to 5
array4[4] = 5 #array[4] is the 5th element

print(array4)


[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


# 17.Scenario: You have a DataFrame and need to find the median of a numeric column.
## a. Question: How would you find the median of the "Scores" column in the following DataFrame?

We can use the code median_score = DataFrame["Scores"].median() to find the median of the numeric column.

# 18.Scenario: You need to filter rows where the value in the "Sales" column is above 100 and then sort these rows by "Date" in descending order.
## a. Question: How would you filter and sort the DataFrame based on the given criteria?

To filter rows where "Sales" is above 100, we can use the following code:
#**************filtered_df = DataFrame[DataFrame["Sales"] > 100]*************#

To sort the filtered rows by "Date" in descending order, we can use the following code:
#**************sorted_df = filtered_df.sort_values(by = "Date", ascending = False)*************#

# 19.Scenario: You have a string containing a number and need to convert it to an integer. Additionally, handle the case where the string might not represent a valid integer.
## a. Question: How would you safely convert the string "42" to an integer and handle invalid cases?

In [ ]:
#need help

# 20.Scenario: You have a list containing different data types, and you want to separate out all the strings.
## a. Question: How would you extract all string elements from the following list?

In [ ]:
#need help